### ISSUE TITLE
Default headers

### ISSUE THREAD

**Issue by Laruxo** [Mitranim/xhttp#10]
Hi, right now using your library with Laravel in the backend. By default it checks if "X-Requested-With" header is set to "XMLHttpRequest". This header is also used by most of the JS frameworks that support ajax (jQuery, Angular, etc.).
Not sure what is your opinion on this header, but I would like to have it added to defaultHeaders.

**Comment by Mitranim** [comment]
It's unnecessary to put special case solutions inside a library when its API is a function. You can add your own defaults by wrapping it:

```js
function ajax (params, onSuccess, onError) {
  params = {
    ...params,
    headers: {
      ...params.headers,
      'X-Requested-With': 'XMLHttpRequest'
    }
  }
  xhttp(params, onSuccess, onError)
}
```

**Comment by Laruxo** [comment]
That is what I already did, just thought that maybe you will want to add this, since it is widely used.
