### ISSUE TITLE
Promise example does not work with ES6-Promise (TypeError)

### ISSUE THREAD

**Issue by ericchaves** [Mitranim/xhttp#11]
I was trying to use xhttp with ES6-Promises following the suggested example code but the code didn't worked, instead I was receiving a TypeError. It seems that es6-promises does not handle multiple values. 

In order to make it work with es6-promises I had to manually call the resolve/reject and use array destructuring in the promise handler, like this:
```
// ajax.js
import {xhttp} from 'xhttp'

export default function ajax(params){
  return new Promise((resolve, reject)=>{
    xhttp(params,
          (body, xhr)   =>{ return resolve([body,   xhr]) },
          (reason, xhr) =>{ return reject( [reason, xhr]) })
  })
}
// some-api.js
return ajax(req)
        .then(([response, xhr]) =>{
          console.log('ajax ok', response, xhr)
        })
        .catch(([error,xhr]) =>{
          console.log('erro', error, xhr)
        })
```

Not sure if other Promises libraries behave the same way but since es6-promises seems to be the future "default implementation" for promises, I though it would worth sharing.

**Comment by Mitranim** [comment]
A promise stands for a single value; `resolve` and `reject` only take one argument. The example in the readme assumes you only want the response. Passing both as a tuple, like you did, is the only way to make both available in a promise.
