### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined on timeout

### ISSUE THREAD

**Issue by Novakov** [Mitranim/xhttp#2]
When request time outs, xhttp fails with error 'Uncaught TypeError: Cannot read property 'forEach' of undefined'. 

Problem is here: https://github.com/Mitranim/xhttp/blob/master/lib/xhttp.js#L135. `parseResponse` expects two parameters (`xhr` and `interceptors`) but gets only one (`xhr`)

**Comment by Mitranim** [comment]
Quite a silly mistake to make. Thanks for noting. Try updating and see if this solves your problem.
