### ISSUE TITLE
Add 'configInterceptor'

### ISSUE THREAD

**Issue by chainlink** [Mitranim/xhttp#3]
Would be nice to have the option to globally set parameters other than data (ie. headers etc). Looks like I can extend the existing interceptors to support this, and can put together a PR

**Comment by Mitranim** [comment]
I think we should just pass `xhr` to request interceptors, like all others. Restricting them to `data` was retarded on my part.

Try replacing line 120 with:
```js
          var result = interceptor(options.data, xhr)
```

And see if this solves your problem.

**Comment by chainlink** [comment]
:+1:

**Comment by chainlink** [comment]
I've created a PR here https://github.com/Mitranim/xhttp/pull/4
I ended up modifying it to pass and return the entire options object for more flexibility. I also removed the `$noBody` check so it works for all requests.

**Comment by Mitranim** [comment]
Merged your PR with some changes:
* request interceptors are called before parsing the options and opening the XMLHttpRequest;
* took an opportunity to clean up the naming of interceptor-related properties and methods (see release notes).

**Comment by chainlink** [comment]
Cool! Thanks :+1:
