### ISSUE TITLE
.catch() just gives the response body

### ISSUE THREAD

**Issue by tarjei** [Mitranim/xhttp#7]
Not the response status-code. 

```javascript
xhttp({url: "some-url-returning-500", method: "GET").catch(response => {
 // response is just response body, not the whole object!
console.log(response)
})
```

Is there a reason for this?

**Comment by Mitranim** [comment]
The `xhr` object is passed to interceptors as a second argument.

**Comment by tarjei** [comment]
But not to the Promises which is where a plain user (like me :P) would expect to find it:
```javascript
xhr.onload = function() {
        if (successful(xhr)) {
          resolve(parseResponse(xhr, xhttp.responseInterceptors))
        } else {
          reject(parseResponse(xhr, xhttp.errorInterceptors))
        }
      }
```

**Comment by Mitranim** [comment]
Pushed a new release (https://github.com/Mitranim/xhttp/releases/tag/0.0.10), please check if the new simplified API helps satisfy your need.

**Comment by tarjei** [comment]
Yep! Thanks a bundle! :)
