### ISSUE TITLE
Compatibility with rollup and ES6 modules

### ISSUE THREAD

**Issue by Laruxo** [Mitranim/xhttp#9]
Hi, first of all let me say that you did a very nice refactoring lately. However, I still have some problems.

Since I saw a jsnext:main attribute in package.json, I thought that this library should work with [rollup](https://github.com/rollup/rollup) and also could be imported as ES6 module. But after trying it out and looking at the code I found some problems.

First of all, for this library to work I must have included CommonJS (otherwise exports variable does not exists). Maybe something like this could be added to allow this library to be used without cjs.
`if (typeof exports === 'undefined') {
  var exports = {}
}`

Second, the module is not exported in ES6 way, so I cannot import it. Maybe an export (`export {xhttp}`) would not break CommonJS modules? I will need to try that.

Lastly, jsnext:main should point to a valid ES6 module, but not to a not compiled file (there are some constants there).
[Rollup wiki](https://github.com/rollup/rollup/wiki/jsnext:main):
> jsnext:main will point to a module that has ES2015 module syntax but otherwise only syntax features that node supports.

[Rollup babel plugin](https://github.com/rollup/rollup-plugin-babel#external-dependencies):
> We encourage library authors not to distribute code that uses untranspiled ES6 features (other than modules) for this reason. Consumers of your library should not have to transpile your ES6 code, any more than they should have to transpile your CoffeeScript, ClojureScript or TypeScript.

**Comment by Mitranim** [comment]
Thanks for commenting on this. It seems that I have misunderstood rollup and how `jsnext:main` is supposed to work.

Added a build step for `jsnext` (https://github.com/Mitranim/xhttp/releases/tag/0.0.12). Please check if this works properly with rollup.

**Comment by Laruxo** [comment]
Thanks, that works very well.
